// AUTO-GENERATED by scripts/gen-commit-history.mjs (runs as `prebuild`).
// Do NOT edit by hand — regenerate with `npm run build` (or `node
// scripts/gen-commit-history.mjs`). Every figure is straight from this repo's
// `git log --all` so the Making-Of graph can never drift false. `windowStart`
// frames the graph to the dense build burst; the earlier days stay recorded for
// truth but sit outside the "how this site was built" window.
export const commitHistory = {
  "total": 109,
  "first": "2023-07-30",
  "last": "2026-07-05",
  "windowStart": "2026-06-20",
  "days": {
    "2026-07-05": 2,
    "2026-07-03": 1,
    "2026-07-01": 5,
    "2026-06-30": 24,
    "2026-06-29": 10,
    "2026-06-28": 2,
    "2026-06-27": 11,
    "2026-06-26": 1,
    "2026-06-25": 3,
    "2026-06-24": 5,
    "2026-06-23": 18,
    "2026-06-22": 5,
    "2026-06-21": 1,
    "2026-06-20": 1,
    "2026-02-08": 3,
    "2026-02-06": 2,
    "2023-11-02": 1,
    "2023-08-25": 1,
    "2023-07-30": 13
  }
};
